# Generated by Django 4.0.6 on 2022-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='count',
            field=models.BooleanField(default=False),
        ),
    ]
