# Generated by Django 4.0.6 on 2022-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='8NMXPN07CFCD1LE1N3Y35NXK', max_length=160, unique=True),
        ),
    ]
