# Generated by Django 4.0.6 on 2022-07-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='HMW3AE36XLDXW08F4HN31KOK', max_length=160, unique=True),
        ),
    ]
