# Generated by Django 4.0.6 on 2022-07-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='K69W2CM5E6QSF7G4YOQ9NJNG', max_length=160, unique=True),
        ),
    ]
