# Generated by Django 4.0.6 on 2022-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='4HIRVGGM5JRB5VSOBDRN05JI', max_length=160, unique=True),
        ),
    ]
