# Generated by Django 4.0.6 on 2022-07-17 16:50

from django.db import migrations, models
import django.db.models.deletion
import main.views


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=main.views.random_generator, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='main.profile'),
        ),
    ]
