# Generated by Django 4.0.6 on 2022-07-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_comentarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['created_on']},
        ),
    ]
