# Generated by Django 4.0.6 on 2022-07-21 19:34

from django.db import migrations, models
import main.views


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_comentarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=main.views.random_generator, max_length=20, unique=True),
        ),
    ]
