# Generated by Django 4.0.6 on 2022-07-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted_from_tweet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='retweet',
                to='main.tweet'),
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
