# Generated by Django 4.0.6 on 2022-07-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tweet_retweeted_from_tweet_delete_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweeted_from_tweet',
            new_name='rt',
        ),
    ]
