# Generated by Django 4.0.6 on 2022-07-22 18:14

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_rename_retweeted_from_tweet_tweet_rt"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 7, 22, 18, 14, 44, 145599, tzinfo=utc)
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "tweet")},
        ),
    ]
