# Generated by Django 4.0.6 on 2022-07-26 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_like_date_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='rt',
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 20, 29, 17, 355460, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_tweet', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='retweet',
                    to='main.tweet')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='retweets',
                    to='main.profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
