# Generated by Django 4.0.6 on 2022-07-26 20:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_tweet_rt_alter_like_date_retweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 20, 38, 19, 157531, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_tweet', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reply',
                    to='main.tweet')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='replies',
                    to='main.profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
