# Generated by Django 4.0.6 on 2022-07-27 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_reply_options_alter_like_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
