# Generated by Django 4.0.6 on 2022-07-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_like_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retweet',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['created_on']},
        ),
    ]
