# Generated by Django 4.0.6 on 2022-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_reply_num_type_retweet_num_type_tweet_num_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='content',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
