# Generated by Django 4.0.6 on 2022-07-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_retweet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='original_tweet',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='main.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets_the',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='retweet', to='main.tweet'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='main.profile'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Retweet',
        ),
    ]
