# Generated by Django 4.0.6 on 2022-08-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='from_user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='to_user',
            new_name='user',
        ),
    ]
