

# Generated by Django 4.0.6 on 2022-08-08 21:28

import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_alter_relationship_follower_alter_relationship_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                default=main.models.random_generator, max_length=20, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(default="curtiu seu tweet", max_length=20),
                ),
                ("viewed", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autor_da_interacao",
                        to="main.profile",
                    ),
                ),
                (
                    "tweet_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tweet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_logado",
                        to="main.profile",
                    ),
                ),
            ],
        ),
    ]
