# Generated by Django 4.0.6 on 2022-08-08 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_profile_nickname_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
